name: vnum
description: A library that enables value based enum behaviour using classes in flutter.
version: 1.2.6+null-safety
homepage: https://github.com/ilmarsad/Flutter_Vnum

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  reflectable: ^3.0.4
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  build_test: any
  json_serializable: ^6.0.1


flutter: